apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-nodeport
spec:
  type: NodePort
  selector:
    app: elasticsearch  # Adjust the label selector as per your Helm chart's labels
  ports:
    - port: 9200  # Port exposed on nodes
      targetPort: 9200  # Port of the Elasticsearch pods
