apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node1
  labels:
    component: node1
spec:
  replicas: 2
  selector:
    matchLabels:
      component: node1
  template:
    metadata:
      labels:
        component: node1
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: "NUMBER_OF_MASTERS"
              value: 1
            - name: cluster.name
              value: es-docker-cluster
            - name: discovery.seed_hosts
              value: node1
            - name: node.name
              value: node1
            - name: xpack.security.enabled
              value: "false"
          image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
          name: node1
          volumeMounts:
            - name: es-pvc
              mountPath: /usr/share/elasticsearch/data
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: es-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
