version: "3"

services:
  node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: node1
    restart: always
    environment:
      - node.name=node1
      - discovery.seed_hosts=node2,node3
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=node1,node2,node3
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - /Users/sarthakagrawal/elasticsearch/es1/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: node2
    restart: always
    environment:
      - node.name=node2
      - discovery.seed_hosts=node1,node3
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=node1,node2,node3
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - /Users/sarthakagrawal/elasticsearch/es2/data:/usr/share/elasticsearch/data

  node3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: node3
    restart: always
    environment:
      - node.name=node3
      - discovery.seed_hosts=node1,node2
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=node1,node2,node3
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - /Users/sarthakagrawal/elasticsearch/es3/data:/usr/share/elasticsearch/data