apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: node1
  name: node1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/kompose-default: "true"
        io.kompose.service: node1
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: cluster.initial_master_nodes
              value: node1,node2,node3
            - name: cluster.name
              value: es-docker-cluster
            - name: discovery.seed_hosts
              value: node2,node3
            - name: node.name
              value: node1
            - name: xpack.security.enabled
              value: "false"
          image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
          name: node1
          ports:
            - containerPort: 9200
              hostPort: 9200
              protocol: TCP
          resources: {}
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: node1-claim0
      restartPolicy: Always
      volumes:
        - name: node1-claim0
          persistentVolumeClaim:
            claimName: node1-claim0
status: {}
