apiVersion: v1
kind: Service
metadata:
  name: node1
spec:
  type: NodePort
  selector:
    component: es-node
  ports:
    - port: 9200 # Port exposed on nodes
      targetPort: 9200 # Port of the Elasticsearch pods
      protocol: TCP
