apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-node
  labels:
    component: es-node
    role: master
spec:
  replicas: 3
  selector:
    matchLabels:
      component: es-node
  template:
    metadata:
      labels:
        component: es-node
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: NUMBER_OF_MASTERS
              value: "3"
            - name: discovery.seed_hosts
              value: "es-node.es-node-0, es-node.es-node-1, es-node.es-node-2"
            - name: cluster.initial_master_nodes
              value: "es-node.es-node-0, es-node.es-node-1, es-node.es-node-2"
            - name: CLUSTER_NAME
              value: es-docker-cluster
            - name: node.roles
              value: "[master]"
            - name: xpack.security.enabled
              value: "false"
          image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
          name: es-node
          volumeMounts:
            - name: es-pvc
              mountPath: /usr/share/elasticsearch/data
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: es-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
