apiVersion: v1
kind: Service
metadata:
  name: es-headless-service
  labels:
    component: headless-service-label
spec:
  clusterIP: None
  selector:
    component: stateful-set-label
  ports:
    - port: 9300
      name: es-transport
