apiVersion: v1
kind: Service
metadata:
  name: node1
spec:
  type: LoadBalancer
  selector:
    component: quickstart
  ports:
    - port: 9200 # Port exposed on nodes
      targetPort: 9200 # Port of the Elasticsearch pods
      protocol: TCP
