apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: elasticsearch-local
  labels:
    component: node2-claim1
  name: node2-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
